In [1]:
import cv2
import numpy as np

# Cargar una imagen desde el archivo
imagen = cv2.imread('Isabel.jpeg')

# Verifica si la imagen se ha cargado correctamente
if imagen is not None:
    # Convierte la imagen en una matriz NumPy
    matriz = np.array(imagen)
    
    # Ahora puedes trabajar con la matriz de la imagen
    print("Matriz de la imagen:")
    print(matriz)
else:
    print("No se pudo cargar la imagen.")


Matriz de la imagen:
[[[130 114  91]
  [129 113  90]
  [128 112  89]
  ...
  [ 23  31  30]
  [ 23  31  30]
  [ 22  30  29]]

 [[130 114  91]
  [129 113  90]
  [128 112  89]
  ...
  [ 23  31  30]
  [ 23  31  30]
  [ 22  30  29]]

 [[130 114  91]
  [130 114  91]
  [129 113  90]
  ...
  [ 23  31  30]
  [ 23  31  30]
  [ 22  30  29]]

 ...

 [[159 132 111]
  [159 132 111]
  [159 132 111]
  ...
  [ 27  33  32]
  [ 27  33  32]
  [ 28  34  33]]

 [[159 132 111]
  [159 132 111]
  [159 132 111]
  ...
  [ 27  33  32]
  [ 27  33  32]
  [ 28  34  33]]

 [[159 132 111]
  [159 132 111]
  [159 132 111]
  ...
  [ 26  32  31]
  [ 25  31  30]
  [ 26  32  31]]]


In [ ]:
cv2.imwrite('matriz_imagen.png', matriz)
cv2.imshow('Mi Imagen', matriz)
cv2.waitKey(0)
cv2.destroyAllWindows()